import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Rubik({ weight: '400', subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: "Personal Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen min-h-screen antialiased'`}> 
        <Providers>
          <Toaster position="top-right"/>
            {children}
        </Providers>
      </body>
    </html>
  );
}
